#!/usr/bin/env bash
# SessionStart — install the `gh` shim in a factory implementer session.
#
# Software-factory design 2d / item 8b. An implementer environment runs in
# pass-through mode with `GH_TOKEN` set to the sentinel `factory-token-required`,
# so *every* `gh` call needs the broker's token, not only the ones START Step 7
# spells out (the tracker's FETCH and DEPENDENCY_PR, `gh pr checks`, the
# review-thread queries, the epic's COORD markers). `factory-token` is a wrapper
# rather than an exporter — an `export` in one Bash call does not reach the next —
# so this hook puts a `gh` shim earlier on PATH that wraps every other invocation.
#
# Step 7 still calls `factory-token exec` explicitly for the push and
# `gh pr create`, so identity never depends on this hook: a branch that deletes it
# leaves those calls wrapped anyway, and any unwrapped `gh` reads the sentinel and
# fails rather than acting as the user. That is the fail-closed outcome 2d wants.
#
# No-op unless FACTORY_BROKER_URL is set (i.e. outside an implementer
# environment). It never blocks a session from starting — but "fails open" means
# the session starts, not that gh stays usable: when the helper cannot mint, the
# hook installs a *deny* shim, because an unwrapped gh in proxy-injected mode
# acts as the user rather than failing.
set -uo pipefail

[ -n "${FACTORY_BROKER_URL:-}" ] || exit 0
[ -n "${CLAUDE_ENV_FILE:-}" ] || exit 0
# Deliberately NOT gated on `command -v gh`: if gh is missing now but appears
# later (a PATH change, a tool install), an unwrapped call would act as the user
# under proxy-injected mode. `factory-token shim` refuses when there is no real
# gh to wrap, and that refusal falls through to the deny shim below, which is
# the fail-closed answer either way.

root="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
helper="$root/scripts/factory-token"
[ -x "$helper" ] || exit 0

# `shim` prints the `export PATH=…` line to stdout and its notes to stderr.
if line=$("$helper" shim 2>/dev/null); then
	printf '%s\n' "$line" >>"$CLAUDE_ENV_FILE" 2>/dev/null || true
	printf 'factory-token: gh shim installed for this session (spec 2d).\n'
	exit 0
fi

# The helper could not mint (no broker, no repo, or proxy-injected mode). Leaving
# `gh` unwrapped is NOT safe here: under proxy-injected mode the git proxy
# substitutes the user's credential, so an early FETCH, DEPENDENCY_PR, or COORD
# call would quietly act as the user — exactly what 2d forbids. Install a shim
# that refuses instead, so the failure is visible at the first gh call rather
# than invisible in the PR's authorship.
deny_dir="${TMPDIR:-/tmp}/factory-token-deny-$(id -u)"
if mkdir -p "$deny_dir" 2>/dev/null; then
	cat >"$deny_dir/gh" <<EOF
#!/usr/bin/env bash
# Generated by the ticket-workflow SessionStart hook: factory-token could not
# mint a token for this session, so gh is refused rather than run as the user.
printf 'gh is refused in this factory session: factory-token could not mint an App token.\n' >&2
printf 'Run "%s" status to see why (exit 3 = proxy-injected mode, i.e. spec 2d M1 is not in effect).\n' $(printf '%q' "$helper") >&2
printf 'Do not work around this by calling gh directly: in proxy-injected mode it acts as the user.\n' >&2
exit 3
EOF
	chmod 755 "$deny_dir/gh" 2>/dev/null || true
	printf 'export PATH=%q\n' "$deny_dir:$PATH" >>"$CLAUDE_ENV_FILE" 2>/dev/null || true
	printf 'factory-token: could not mint an App token, so gh is REFUSED for this session (a deny shim is first on PATH). Run "%s" status to see why; do not bypass it, since an unwrapped gh can act as the user.\n' "$helper" >&2
else
	printf 'factory-token: could not mint an App token and could not install the deny shim. Treat every gh call in this session as untrusted for identity: run "%s" status before pushing or opening a PR.\n' "$helper" >&2
fi
exit 0
